SREP-1037 Generate SelectorSyncSet files
openshift/osd-operators-registry pull request #17
Opened 2019-04-15 19:59 UTC by rogbas

Added `SelectorSyncSet` generation for each operator, the output will be on manifests/ folder.

I kept the original operator.yaml templates and outputs so we can also deploy locally or in test environments without using `SyncSets`

I'm proposing `managed-osd` as the namespace where the `SelectorSyncSets` will be placed in a hive cluster, feel free to comment/propose another name.

2019-04-15 20:44 UTC, jewzaam requested changes
Two things I would change:

1. SelectorSyncSet is Cluster scoped, no need for SYNCSET_NAMESPACE
2. Put generated manifests into a sub-directory so it's easier to manually apply one vs the other

2019-04-15 20:51 UTC, mwoodson approved these changes

2019-04-15 20:52 UTC, mwoodson commented
I'm :+1: 

I don't know the whole picture here, so I don't understand the details all that well.  This looks like it's doing sane things

2019-04-15 20:54 UTC, rogbas commented
> 2. Put generated manifests into a sub-directory so it's easier to manually apply one vs the other
Do you mean creating subfolders under `manifests/` like: `manifests/local/` and `manifests/hive/` ?

2019-04-15 20:57 UTC, jewzaam commented
@rogbas I would leave what we have where it is and put new selectorsyncset files in `manifests/hive/`

2019-04-15 21:00 UTC, jewzaam requested changes
@rogbas just noticed this is missing generation of selectorsyncset for the CatalogSource

2019-04-15 21:34 UTC, rogbas commented
Pushed changes including:
 * SelectorSyncSets yaml being generated under `manifests/hive/`
 * Generate SelectorSyncSet for `CatalogSource`
 * Operator's SSSs are being prefixed with `osd-` to facilitate identification

2019-04-15 21:51 UTC, jewzaam commented
/lgtm

2019-04-15 21:51 UTC, jewzaam approved these changes

2019-04-16 13:59 UTC, rogbas commented
/lgtm

2019-04-16 14:00 UTC, jewzaam requested changes
Need to change `manifestdir` target to `mkdir -d $(MANIFESTDIR)/hive`
https://github.com/openshift/osd-operators-registry/pull/17/files#diff-b67911656ef5d18c4ae36cb6741b7965R67

2019-04-16 14:12 UTC, rogbas commented
/lgtm

@jewzaam I can't lgtm my own PR,

2019-04-16 14:36 UTC, jewzaam approved these changes

2019-04-16 14:36 UTC, jewzaam commented
/lgtm

2019-04-16 17:18 UTC, merged